<?php

namespace Database\Seeders;

use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class ConceptosCobolSeeder extends Seeder
{
    public function run(): void
    {
        $ahora = now();

        $conceptos = [
            ['dominio' => 'PROP', 'codigo' => '01', 'descripcion' => 'ALQUILERES', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '02', 'descripcion' => 'REEMBOLSO IMPUESTOS', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '03', 'descripcion' => 'REEMBOLSO INDEMNIZACION', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '04', 'descripcion' => 'OTROS CREDITOS', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '05', 'descripcion' => 'CLAUSULA PENAL', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '06', 'descripcion' => 'INTS.por MORA S/IMPTOS.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '07', 'descripcion' => 'CRED. I.V.A.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '08', 'descripcion' => 'CRED.I.V.A. ACR.RESP.NO INSC.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '09', 'descripcion' => 'REEMBOLSO DE REPARACIONES', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '10', 'descripcion' => 'INTS.P/MORA S/OTROS CONCEPTOS', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '11', 'descripcion' => 'OTROS CREDITOS ( INQUILINO )', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '12', 'descripcion' => 'ACRED.IVA.COCH.PROP.INSCR.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '13', 'descripcion' => 'DEV.PERC.NoCATEG.EN IVA', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '14', 'descripcion' => 'ACR.COMISION TARJ.SUQUIA', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '15', 'descripcion' => 'CR.COMIS.P/ACRED.INDEB.ALQ.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '16', 'descripcion' => 'CR.COMIS.P/ACRED.INDEB.INDEMNIZ.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '17', 'descripcion' => 'CR.COMIS.P/DEB.INDEB.DE IMPTOS.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '18', 'descripcion' => 'BONIF.P/SIST.COMIS.DIFERENC.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '19', 'descripcion' => 'TRASPASO SALDO ANTERIOR', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '20', 'descripcion' => 'CANCELACION SALDOS DEUDORES', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '21', 'descripcion' => 'Comision p/Admin.Alquileres', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '22', 'descripcion' => 'Com.s/Imp,ExpyServ', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '23', 'descripcion' => 'Comision Reemb.Impuestos', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '24', 'descripcion' => 'Comision p/Admin.Cl.Penal', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '25', 'descripcion' => 'Comision p/admin.Indemnizac.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '26', 'descripcion' => 'Debito iva Cochera Prop.Inscr.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '27', 'descripcion' => 'Percepcion NoCateg.en IVA', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '29', 'descripcion' => 'Liquido Abonado', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '31', 'descripcion' => 'Pago Imptos del mes s/detalle', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '32', 'descripcion' => 'Ret.Efectivo - Pago de Gastos.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '33', 'descripcion' => 'Acreditac.Indebida de Alquileres', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '34', 'descripcion' => 'Comision Pago Imp.Garantiz.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '35', 'descripcion' => 'Acredit.Indebida de Indemnizac.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '36', 'descripcion' => 'I.v.a.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '37', 'descripcion' => 'I.v.a.Acr.Resp.No Inscr.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '38', 'descripcion' => 'Traspaso Saldo Deudor Liquid.Anterior', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '39', 'descripcion' => 'Traspaso saldo anterior', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '40', 'descripcion' => 'Acred.Indeb.Imp.No Garant.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '41', 'descripcion' => 'Acr.Indeb.Ints.p/Mora Imp.No Gar', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '42', 'descripcion' => 'Debito Reparaciones', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '43', 'descripcion' => 'Otros Debitos (Ree.a Inquil.)', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '44', 'descripcion' => 'Acr.Indeb.Ints.p/mora Otr.conceptos.', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '45', 'descripcion' => 'Acredit.Indebida Cl.Penal', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'PROP', 'codigo' => '46', 'descripcion' => 'SEGURO SAN CRISTOBAL', 'origen_cobol' => 'TABLACOD'],
            ['dominio' => 'INQ', 'codigo' => '01', 'descripcion' => 'ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '02', 'descripcion' => 'INTS.COMPENS.S/ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '03', 'descripcion' => 'IMPUESTOS G.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '04', 'descripcion' => 'INTS.COMPENS S/IMPTOS GARANT', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '05', 'descripcion' => 'COM.S/REE.IMP.EXPoSERV', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '06', 'descripcion' => 'COMISION P/ADMINIST.EXPENSAS', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '07', 'descripcion' => 'SELLADO DE CONTRATO', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '08', 'descripcion' => 'HONOR P/INTERMEDIACION', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '09', 'descripcion' => 'GASTOS NOTIFICACIONES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '10', 'descripcion' => 'GASTOS JUDICIALES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '11', 'descripcion' => 'INTS.COMPENS S/OTR CONC.Empresa', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '12', 'descripcion' => 'OTROS DEBITOS (Empresa)', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '13', 'descripcion' => 'SEGURO SAN CRISTOBAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '14', 'descripcion' => 'GASTOS P/DEP O TRANSF BANCARIAS', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '15', 'descripcion' => 'GAST.ADMINISTR. F/CR. R.N.I.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '16', 'descripcion' => 'PERCEPCION No CATEG.EN IVA', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '17', 'descripcion' => 'IVA S/ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '18', 'descripcion' => 'ACREC.IVA S/ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '19', 'descripcion' => 'PERC.NoCAT IVA S/ALQUIL.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '21', 'descripcion' => 'CLAUSULA PENAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '23', 'descripcion' => 'IMPUESTOS N.G.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '24', 'descripcion' => 'INTS.COMPENS S/IMPTO.NO GARANT.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '25', 'descripcion' => 'REPARACIONES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '26', 'descripcion' => 'INDEMNIZAC P/RESOL CONTR', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '27', 'descripcion' => 'OTROS DEBITOS (Propiet)', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '28', 'descripcion' => 'INTS.P/MORA(OTROS CONC.) Propiet.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '30', 'descripcion' => 'INTS.P/MORA ALQ.CARGA MANUAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '31', 'descripcion' => 'INTS.P/MORA CONC.GeI.CARGA MANUAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '32', 'descripcion' => 'INTS.P/MORA CONC.PROP.CARGA MANUAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '46', 'descripcion' => 'I.V.A.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '47', 'descripcion' => 'I.V.A. ACR.RESP.NO INSCR.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '48', 'descripcion' => 'TRASPASO SALDO ANTERIOR', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '49', 'descripcion' => 'De/INTERESES POR MORA', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '51', 'descripcion' => 'DEVOL.ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '52', 'descripcion' => 'DEVOL.INTS.P/MORA S/ ALQUIL.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '53', 'descripcion' => 'DEVOL.IMPUESTOS GARANTIZADOS', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '54', 'descripcion' => 'DEVOL.INT.P/MORA S/IMP.GARANT.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '55', 'descripcion' => 'DEVOL.COMIS. S/ REEMB.IMPUEST.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '56', 'descripcion' => 'DEVOL.COMIS.P/ADMINIST.DE PROPIED.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '57', 'descripcion' => 'DEVOL.SELLADO CONTRATO', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '58', 'descripcion' => 'DEVOL.GASTOS ADMINISTRATIVOS', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '59', 'descripcion' => 'DEVOL.GASTOS NOTIFICACIONES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '60', 'descripcion' => 'DEVOL.GASTOS JUDICIALES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '61', 'descripcion' => 'DEVOL.INTS.P/ MORA(OTR.CONC.)Empresa', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '62', 'descripcion' => 'OTROS CREDITOS (Empresa)', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '63', 'descripcion' => null, 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '64', 'descripcion' => 'DEVOL.GAST.ADMIN.F/CR. R.I.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '65', 'descripcion' => 'DEVOL.GAST.ADMIN. F/CR. R.N.I.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '66', 'descripcion' => 'DEV.PERC.NoCAT.EN I.V.A.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '67', 'descripcion' => 'DEV.IVA S/ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '68', 'descripcion' => 'DEV.ACREC.IVA S/ALQUILERES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '69', 'descripcion' => 'DEV.PERC.NoCAT IVA S/ALQ.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '71', 'descripcion' => 'DEVOL.CLAUSULA PENAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '73', 'descripcion' => 'DEVOL.IMPUESTOS NO GARANTIZADOS', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '74', 'descripcion' => 'DEVOL.INTS.P/MORA IMP.NO GARANT.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '75', 'descripcion' => 'DEVOL.REPARACIONES', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '76', 'descripcion' => 'DEVOL.INDEMNIZACION', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '77', 'descripcion' => 'OTROS CREDITOS (Propiet.)', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '78', 'descripcion' => 'DEVOL.INTS. P/MORA (OTROS CONC.)Prop.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '80', 'descripcion' => 'DEVOL.INTS.P/MORA ALQ.CARGA MANUAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '81', 'descripcion' => 'DEVOL.INTS.P/MORA CONC.GeI CARGA MANUAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '82', 'descripcion' => 'DEVOL.INTS.MORA CONC.PROP.CARGA MANUAL', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '88', 'descripcion' => 'TRASPASO SALDO ANTERIOR', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '90', 'descripcion' => 'SU PAGO', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '91', 'descripcion' => 'Cr/INTERESES POR MORA', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '97', 'descripcion' => 'DEVOL. I.V.A.', 'origen_cobol' => 'INQTABCODI'],
            ['dominio' => 'INQ', 'codigo' => '98', 'descripcion' => 'DEVOL.I.V.A. ACREC.NO INSC.', 'origen_cobol' => 'INQTABCODI'],
        ];

        foreach ($conceptos as $concepto) {
            DB::table('conceptos')->updateOrInsert(
                [
                    'dominio' => $concepto['dominio'],
                    'codigo' => $concepto['codigo'],
                ],
                [
                    'descripcion' => $concepto['descripcion'],
                    'activo' => true,
                    'origen_cobol' => $concepto['origen_cobol'],
                    'updated_at' => $ahora,
                    'created_at' => $ahora,
                ]
            );
        }
    }
}
